### ISSUE TITLE
beginner questions :)

### ISSUE THREAD

**Issue by salcin** [lipoja/AMSpi#1]
Hi,

Thank you for sharing your work, I start on Raspberry and I have some problems at the connections.

Following your tutorial I am confronted with two problems, Could you help me to understand
1. On your diagram it has GPIO16 with a pink ball but on the motor shield I do not find this color.
2. The red wire on the motor shield is for the pin 5V or the pin just below ?

Thank you in advance.

**Comment by lipoja** [comment]
Hello,
1. Thank you for letting me know about the diagram. I've uploaded fixed version of wiring image.
2. The red wire is for pin where you can connect 5V input to motor shield. It is the one covered with the red color. (near the edge)

Thank you.

**Comment by salcin** [comment]
Thank you alot thanks to your tutorial and your explanations my wheel turns finally.

I'm happy as a kid :)
