### ISSUE TITLE
i need to use only 2 dc motors plus 2 servo motors 

### ISSUE THREAD

**Issue by Darth-Kronos** [lipoja/AMSpi#5]
could u pls me help me with the connections and what part of the code shld me removed to make it work?

**Comment by Darth-Kronos** [comment]
amspi.set_74HC595_pins(21, 20, 16)
        # Set PINs for controlling all 4 motors (GPIO numbering)
        amspi.set_L293D_pins(5, 6, 13, 19)
in the above code 5 means motor1 6 motor2 13 motor3 19 motor 4?
if yes i hav to just 
amspi.set_L293D_pins(5,6)
?

**Comment by lipoja** [comment]
Yes. It should be enough to call `amspi.set_L293D_pins(5,6)`

**Comment by Darth-Kronos** [comment]
and speed = 50 for 50% of the speed is not working
motors run for a sec and stop only at speed=100 or None it is working fine
